CREATE SEQUENCE SEQ_MOTORISTAS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_MOTORISTAS (
    ID_MOTORISTA INTEGER DEFAULT SEQ_MOTORISTAS.NEXTVAL NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(14) NOT NULL,
    ENDERECO VARCHAR2(200),
    TELEFONE VARCHAR2(20),
    CNH_NUMERO VARCHAR2(20) NOT NULL,
    CNH_CATEGORIA VARCHAR2(10) NOT NULL,
    CNH_VALIDADE DATE NOT NULL
);