CREATE SEQUENCE SEQ_VEICULOS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_VEICULOS (
    ID_VEICULO INTEGER DEFAULT SEQ_VEICULOS.NEXTVAL NOT NULL PRIMARY KEY,
    TIPO_VEICULO VARCHAR2(50),
    MODELO VARCHAR2(100),
    ANO_FABRICACAO NUMBER,
    PLACA VARCHAR2(20),
    OUTROS_DETALHES VARCHAR2(255)
);