CREATE SEQUENCE SEQ_ROTAS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_ROTAS (
    ID_ROTA INTEGER DEFAULT SEQ_ROTAS.NEXTVAL NOT NULL  PRIMARY KEY,
    ORIGEM VARCHAR2(100),
    DESTINO VARCHAR2(100),
    DISTANCIA NUMBER,
    TEMPO_MEDIO NUMBER,
    CONDICOES_ESPECIAIS VARCHAR2(255),
	VELOCIDADE_MAXIMA_PERMITIDA NUMBER
);