CREATE SEQUENCE SEQ_INCIDENTES
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_INCIDENTES (
    ID_INCIDENTE INTEGER DEFAULT SEQ_INCIDENTES.NEXTVAL NOT NULL PRIMARY KEY,
    TIPO_INCIDENTE VARCHAR2(100),
    LOCALIZACAO VARCHAR2(200),
    DESCRICAO VARCHAR2(1000),
    DATA_HORA TIMESTAMP,
    STATUS VARCHAR2(20)
);