CREATE SEQUENCE SEQ_REGISTRO_TRAFEGO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_REGISTRO_TRAFEGO (
    REGISTRO_ID INTEGER DEFAULT SEQ_REGISTRO_TRAFEGO.NEXTVAL NOT NULL PRIMARY KEY,
    ID_VEICULO NUMBER,
    ID_MOTORISTA NUMBER,
    ID_ROTA NUMBER,
    DATA_HORA TIMESTAMP,
    VELOCIDADE_VEICULO NUMBER,
    CONDICOES_METEREOLOGICAS VARCHAR2(100),
    OUTROS_DADOS VARCHAR2(255),
    FOREIGN KEY (ID_VEICULO) REFERENCES TBL_VEICULOS(ID_VEICULO),
    FOREIGN KEY (ID_MOTORISTA) REFERENCES TBL_MOTORISTAS(ID_MOTORISTA),
    FOREIGN KEY (ID_ROTA) REFERENCES TBL_ROTAS(ID_ROTA)
);