name: Continuous Delivery 1.0

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: api-trafego

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Git Checkout
          uses: actions/checkout@v4

        - name: Setup Java SDK
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{github.sha}}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
          - name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: 'api-trafego-dev'
              publish-profile: ${{ secrets.AZURE_PROFILE }}
              images: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{github.sha}}'