name: Continuous Delivery 1.0

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: api-trafego

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Git Checkout
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to registry
          uses: docker/login-action@v2
          with:
            registry: https://index.docker.io/v1/
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{github.sha}}
            file: ./Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
          - name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: 'api-trafego-dev'
              slot-name: 'production'
              publish-profile: ${{ secrets.AZURE_PROFILE }}
              images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{github.sha}}'